### ISSUE TITLE
final submission checklist

### ISSUE THREAD

**Issue by teixeirak** [forc-db/Global_Productivity#129]
- [x] @beckybanbury final check
- [x] @teixeirak final check
- [x] cite ERL review
- [x] issue #126 
- [x] issue #105 (@beckybanbury )
- [x] make repo public, archive in Zenodo, add DOI (@teixeirak )
- [ ] we probably have to make word versions of the tables.

**Comment by teixeirak** [comment]
@beckybanbury , I've made the repo public and archived on Zenodo: https://zenodo.org/record/4563099#.YDgQgmNOlN0. Here's the DOI : 10.5281/zenodo.4563099.

**Comment by teixeirak** [comment]
@beckybanbury , I've taken care of the points above. Have you finished a final check?

Note that we might (probably) still need to make word versions of the tables. I'll know for sure when I start the submission process (ASAP, but not sure I'll get to it today).

**Comment by beckybanbury** [comment]
Just to check - is the "Anderson Teixeira n.d." reference the ERL review, or is that a knitting error?

**Comment by beckybanbury** [comment]
I'm happy with this - I've made one tiny edit (are you able to knit this again?) but otherwise it looks good to me!

**Comment by teixeirak** [comment]
Awesome! I will work on submitting as soon as I get a chance.

Yes, the n.d. Reference is the ERL review. I assume that it will be accepted by the time we get the proofs.
