### ISSUE TITLE
polishing figures, tables, & analyses

### ISSUE THREAD

**Issue by teixeirak** [forc-db/Global_Productivity#25]
## analyses
- [x] be consistent in the set of variables presented (although not every variable has to appear in every figure/ table). Currently, Table 1, Fig. 1, Fig. 2, etc. have different sets of variables. See issue #26.

## figures
general:
- [x] it would be helpful to have a single color for each variable that is consistent across all figures.
- [x] it would also be helpful to have different shapes for each variable, again consistent across all figures. This would be particularly valuable when people print it in black & white.

Fig. 1 (map):
- [x] display consistent set of variables (#26)

Fig. 2 (all variables scaled): 
- [x] display consistent set of variables (#26)

Fig. 3 (stacked plots): 
- [x] as mentioned under general comments, use the same color/symbol for each variable. This will be particularly valuable here in that it will make it easy to identify variables repeated across plots, and therefore how the figure shows subsidiary components of various fluxes
- [x] reorder: (a) GPP = NPP + R_auto, (b) NPP = ANPP + BNPP, (c) ANPP = ANPP_foliage+ ANPP_woody_stem, (d) BNPP_root, BNPP_root_fine, R_root, TBCF (total belowground C flux; no data-- just summed line)= BNPP_root+R_root 
- [x] remove numbers on variables, just list as e.g., "ANPP + BNPP" (rather than "sum of (1) + (2)")
- [x] add x-axis labels

Fig. 4 (responses to climate variables):
- [x] reconsider which climate variables to display:  Temp seasonality and temp annual range should be quite closely correlated (right?), so I don't think it makes sense to include both. Also, I'd stay away from vapour pressure. I think that vapor pressure deficit would be a much better choice. It may be good to show either precipitation or precipitation seasonality, whichever explains more variation (even though they're not the strongest predictors, I think most readers will be very interested to see those relationships.)

Fig. 5 (ratio tests):
- [x] drop ANPP_woody (issue #22 )
- [x] adjust y-axis so that max is 2 instead of 3.
